openapi: 3.0.0
info:
  title: "Vend-O-Matic API"
  description: "a web service supporting a beverage vending machine"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Item:
      type: "object"
      required:
        - brand_name
      properties:
        brand_name:
          type: "string"
        quantity:
          type: "integer"
  parameters:
    brand_name:
      name: "brand_name"
      description: "Name of inventory item to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /inventory:
    get:
      operationId: "inventory.read_all"
      tags:
        - "Inventory"
      summary: "Read the array of available inventory items"
      responses:
        "200":
          description: "Successfully read the remaining item quantities in the inventory (an array of integers)"
    post:
      operationId: "inventory.create"
      tags:
        - Inventory
      summary: "Create an Item"
      requestBody:
          description: "Item to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "item"
                $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: "Successfully created an Item"